# services:
#   # backend:
#   #   build:
#   #     context: ./Backened
#   #     dockerfile: Dockerfile
#   #   ports:
#   #     - "5000:5000"
#   #   environment:
#   #     - CLIENT_ID=dea716ed40cc40b79f656f9fcbec3a02
#   #     - CLIENT_SECRET=c877d293b0f04c4fa2dabe10a96173b1
#   #     - FLASK_APP=app.py
#   #     - FLASK_ENV=development
#   #   depends_on:
#   #     - redis
#   #   networks:
#   #     - app-network

#   redis:
#     image: redis:latest
#     ports:
#       - "6379:6379"
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge


version: "3.8"

services:
  backend:
    build:
      context: ./Backened
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - CLIENT_ID=dea716ed40cc40b79f656f9fcbec3a02
      - CLIENT_SECRET=c877d293b0f04c4fa2dabe10a96173b1
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_HOST=redis  # Add Redis host environment variable
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: software-project-redis-1
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge




